package com.yc.shoesMall.bean;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(value = { "handler" })
public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
	
	private Product product;
		
	
    public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.uid
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.pid
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_count
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.create_time
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_size
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    private String productSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_image
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    private String productImage;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param id the value for cart.id
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.uid
     *
     * @return the value of cart.uid
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.uid
     *
     * @param uid the value for cart.uid
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.pid
     *
     * @return the value of cart.pid
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.pid
     *
     * @param pid the value for cart.pid
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_count
     *
     * @return the value of cart.product_count
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_count
     *
     * @param productCount the value for cart.product_count
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.create_time
     *
     * @return the value of cart.create_time
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.create_time
     *
     * @param createTime the value for cart.create_time
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_size
     *
     * @return the value of cart.product_size
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public String getProductSize() {
        return productSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_size
     *
     * @param productSize the value for cart.product_size
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setProductSize(String productSize) {
        this.productSize = productSize == null ? null : productSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_image
     *
     * @return the value of cart.product_image
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_image
     *
     * @param productImage the value for cart.product_image
     *
     * @mbg.generated Thu Sep 05 21:14:45 CST 2019
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }
}